#' @param initial.population [\code{list}]\cr
#'   List of individuals which should be placed in the initial population.
#'   The function will stop with an error message if the number of passed individuals
#'   is larger than \code{control$n.population}. If the number of passed individuals
#'   is lower than \code{control$n.population}, the population will be filled up
#'   by individuals generated by the corresponding generator.
#'   Default is \code{NULL}, i.e., the entire population is generated by the
#'   population generator.
